services:
  - type: web
    name: tcgplayer-scraper
    env: node
    plan: free
    buildCommand: ./render-build.sh
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
